image: viki/node:0.12.9
git:
  depth: 1
script:
  - ls -lth pull/repos/tethys/
publish:
  docker:
    docker_host: $$docker_host
    docker_version: 1.6.2
    registry_login: true
    registry_login_url: https://index.docker.io/v1/
    username: $$docker_username
    password: $$docker_password
    email: $$docker_email
    image_name: viki/swagger-editor
    keep_build: true
deploy:
  bash:
    script:
      - echo "Hello docker"
    when:
      branch: master
