clone:
  depth: 2

cache:
  mount:
    - /drone/docker

build:
  image: viki/node:0.12.9
  auth_config:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
  commands:
    - npm install
notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: drone-ci
    username: Drone

publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: viki/swagger-editor
    tag:
      - "$${COMMIT:0:7}"
      - latest
